samples:

   

genomes:
    filter_rna : ./data/genomes/filter_rna/file_name_here
    chloro_mitochondria : ./data/genomes/chloroplast_mitocondrion/file_name_here
    reference_genome : ./data/genomes/reference_genome/file_name_here

paths:
    trim_galore : trim_galore
    bowtie : bowtie
    ShortStack : ShortStack
    samtools : samtools


trim:
    min_length : 23
    max_length : 23
    adapter_seq : 
    quality : 30


filter_rfam:
    threads : 1
    

filter_c_m:
    threads : 1


cluster:
    bowtie_cores : 1


convert_1:
    threads : 1
