samples:


genomes:
    filter_rna : ./data/genomes/filter_rna/
    chloro_mitochondria : ./data/genomes/chloroplast_mitocondrion/
    reference_genome : ./data/genomes/reference_genome/


paths:
    trim_galore : trim_galore
    bowtie : bowtie
    ShortStack : ShortStack
    samtools : samtools


trim:
    min_length : 21
    max_length : 24
    adapter_seq : 
    quality : 30


filter_rfam:
    threads : 1
    

filter_c_m:
    threads : 1


cluster:
    bowtie_cores : 1


convert_1:
    threads : 1
