samples:

    
trim:
    min_length : 19
    max_length : 26
    adapter_seq : "AGATCGGAAGAGCACACGTCTGAACTCCAGTCA"
    quality : 30

filter_rfam:
    genome : ./data/genomes/rfam_athaliana/rfam_14_nomirna_a_thaliana

filter_c_m:
    genome : ./data/genomes/chloroplast_mitocondrion_bowtie-index/TAIR10_chrCM

cluster:
    bowtie_cores : 1
    genome : ./data/genomes/ro18_v2_fixed_ids_shortstack-index/ro18_v2_standard_output.final.scaffolds.fixed_ids.fasta