samples:
     - Sample_TK5-14

threads: 
    filter_rna_bowtie : 1
    filter_c_m_bowtie : 1
    shortstack_cluster : 1
    mapped_reads_samtools : 1

genomes:
    filter_rna : ./genomes/filter_rna/arabidopsis_brassica_rfam
    chloro_mitochondria : ./genomes/chloroplast_mitocondrion/TAIR10_chrCM
    reference_genome : ./genomes/reference_genome/ro18_v2_standard_output.final.scaffolds.fixed_ids.fasta


paths:
    trim_galore : trim_galore
    bowtie : bowtie
    ShortStack : ShortStack
    samtools : samtools


trim:
    min_length : 19
    max_length : 26
    adapter_seq : --illumina
    quality : 30