samples:
    - TK1_01_S1_L001_R1_001
    - TK1_02_S2_L001_R1_001
    - TK1_03_S3_L001_R1_001
    - TK1_04_S4_L001_R1_001

    
trim:
    min_length : 19
    max_length : 26
    adapter_seq : "AGATCGGAAGAGCACACGTCTGAACTCCAGTCA"
    quality : 30

filter_rfam:
    genome : ./data/genomes/rfam_athaliana/rfam_14_nomirna_a_thaliana

filter_c_m:
    genome : ./data/genomes/chloroplast_mitocondrion_bowtie-index/TAIR10_chrCM