trimming: 
    min_length : 19
    max_length : 26
    adapter_seq : TGGAATTCTCGG
    quality : 30
 
threads: 
    filter_rna_bowtie : 10 
    filter_c_m_bowtie : 10 
    shortstack_cluster : 10 
    mapped_reads_samtools : 10 
 
paths: 
    trim_galore : trim_galore
    bowtie : bowtie
    ShortStack : ShortStack
    samtools : samtools
 
samples: 
    - TK2_20_S44_L002_R1_001
    - TK4_9_S8_R1_001-f
 
genomes: 
    chloro_mitochondria : ./genomes/chloro_mitocondrion/TAIR10_chrCM
    filter_rna : ./genomes/filter_rna/arabidopsis_brassica_rfam
    reference_genome : ./genomes/reference_genome/ro18_v2_standard_output.final.scaffolds.fixed_ids.fasta
