trimming: 
    min_length : 19
    max_length : 26
    adapter_seq : TGGAATTCTCGG
    quality : 30
 
threads: 
    filter_rna_bowtie : 10 
    filter_c_m_bowtie : 10 
    shortstack_cluster : 10 
    mapped_reads_samtools : 10 
 
paths: 
    trim_galore : trim_galore
    bowtie : bowtie
    ShortStack : ShortStack
    samtools : samtools
 
samples: 

genomes: 
    chloro_mitochondria : ./genomes/chloro_mitocondrion/
    filter_rna : ./genomes/filter_rna/
    reference_genome : ./genomes/reference_genome/
