samples:
   - sample1
    
trim:
    min_length : 19
    max_length : 26
    adapter_seq : "AGATCGGAAGAGCACACGTCTGAACTCCAGTCA"
    quality : 30

filter_rfam:
    genome : ./data/genomes/

filter_c_m:
    genome : ./data/genomes/

cluster:
    bowtie_cores : 1
    genome : ./data/genomes/
